### ISSUE TITLE
Komutlar Çalışmıyor

### ISSUE THREAD

**Issue by Khasimoff** [ArdaGnsrn/IslandLeaderboard#2]
Öncelikle merhaba. ekletiyi sunucuma ekledim ve yeniden başlatdım. Eklenti dosyaları geldi config.yml dosyasına girdim ayarlamaları yapdım ve sunucuyu yeniden başlatdım. Oyuna girdim fakat plugine aid hiçbir komut çalışımıyordu. Komutu yazdıktan sonra ne oyundan nede konsoldan bir mesaj geldi. Yani tepki yok. 
Spigot sürümü: 1.8.8
Birde leaderos için bir rehber oluştururmusunuz. (nasıl sıralama eklenir)

**Comment by ArdaGnsrn** [comment]
**Merhabalar,**
Daha detaylı yardımcı olabilmek adında eğer discord kullanıyorsanız ArdaGnsrn # 0001 kullanıcı adını arkadaş olarak ekleyebilir misiniz?

**Comment by ArdaGnsrn** [comment]
Sorun düzeltildi. Güncelleme olarak gönderilecektir.
